
'use server';
/**
 * @fileOverview A flow to handle Microsoft OAuth 2.0 token exchange using PKCE.
 * This file is responsible for securely exchanging an authorization code,
 * received from Microsoft after user consent, for an access and refresh token.
 *
 * - exchangeCodeForToken - Exchanges an authorization code for an access token.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';
import type { MicrosoftAuthTokens } from '@/types';

// Input schema for the token exchange flow.
const ExchangeCodeInputSchema = z.object({
  code: z.string().describe('The authorization code received from Microsoft.'),
  codeVerifier: z.string().describe('The PKCE code verifier generated by the client.'),
  redirectUri: z.string().url().describe('The redirect URI used in the initial auth request.'),
});

// Output schema for the token exchange flow, matching Microsoft's response.
const ExchangeCodeOutputSchema = z.object({
    token_type: z.string(),
    scope: z.string(),
    expires_in: z.number(),
    access_token: z.string(),
    refresh_token: z.string(),
});

/**
 * Publicly exported function that can be called from the frontend.
 * It acts as a wrapper around the Genkit flow for Microsoft token exchange.
 * @param input The input object containing the code, verifier, and redirect URI.
 * @returns A promise that resolves to the Microsoft token data.
 */
export async function exchangeCodeForToken(
    input: z.infer<typeof ExchangeCodeInputSchema>
): Promise<MicrosoftAuthTokens> {
  return exchangeCodeFlow(input);
}

// Defines the Genkit flow for handling the Microsoft token exchange.
const exchangeCodeFlow = ai.defineFlow(
  {
    name: 'exchangeMicrosoftCodeForTokenFlow',
    inputSchema: ExchangeCodeInputSchema,
    outputSchema: ExchangeCodeOutputSchema,
  },
  async ({ code, codeVerifier, redirectUri }) => {
    // Retrieve Microsoft OAuth credentials from environment variables.
    // These must be configured on the server for this flow to work.
    const clientId = process.env.MICROSOFT_CLIENT_ID;

    if (!clientId) {
      throw new Error("Microsoft OAuth Client ID is not configured on the server.");
    }

    try {
      // The token endpoint for Microsoft's universal ('common') tenant.
      const tokenUrl = "https://login.microsoftonline.com/common/oauth2/v2.0/token";
      
      // Construct the body for the POST request.
      const body = new URLSearchParams({
        client_id: clientId,
        scope: "openid offline_access Calendars.Read User.Read Notes.Read", // Must match scopes from auth request
        code,
        redirect_uri: redirectUri,
        grant_type: "authorization_code",
        code_verifier: codeVerifier, // PKCE-specific parameter
      });

      // Perform a POST request to Microsoft's token endpoint.
      const response = await fetch(tokenUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
        },
        body: body.toString(),
      });

      const data = await response.json();

      // If the response is not OK, throw an error with the description from Microsoft.
      if (!response.ok) {
        console.error("Error exchanging Microsoft code for token:", data);
        throw new Error(data.error_description || "Failed to exchange code for token.");
      }

      // Return the token data on success.
      return data as MicrosoftAuthTokens;

    } catch (e: any) {
      console.error("Error in exchangeMicrosoftCodeForTokenFlow:", e);
      // Re-throw the error to be handled by the caller.
      throw new Error(`An unexpected error occurred during Microsoft token exchange: ${e.message}`);
    }
  }
);
